// Copyright © 2010 - May 2014 Rise Vision Incorporated.
// Use of this software is governed by the GPLv3 license
// (reproduced in the LICENSE file).

package com.risevision.ui.client.common.widgets;


public class CountryWidget extends RiseListBox{
	public CountryWidget() {
		loadData();
	}

	private void loadData() {
		addItem("< Select Country >", "");
		addItem("Afghanistan", "AF");
		addItem("Albania", "AL");
		addItem("Algeria", "DZ");
		addItem("American Samoa", "AS");
		addItem("Andorra", "AD");
		addItem("Angola", "AO");
		addItem("Anguilla", "AI");
		addItem("Antarctica", "AQ");
		addItem("Antigua and Barbuda", "AG");
		addItem("Argentina", "AR");
		addItem("Armenia", "AM");
		addItem("Aruba", "AW");
		addItem("Australia", "AU");
		addItem("Austria", "AT");
		addItem("Azerbaijan", "AZ");
		addItem("Bahamas", "BS");
		addItem("Bahrain", "BH");
		addItem("Bangladesh", "BD");
		addItem("Barbados", "BB");
		addItem("Belarus", "BY");
		addItem("Belgium", "BE");
		addItem("Belize", "BZ");
		addItem("Benin", "BJ");
		addItem("Bermuda", "BM");
		addItem("Bhutan", "BT");
		addItem("Bolivia", "BO");
		addItem("Bosnia and Herzegovina", "BA");
		addItem("Botswana", "BW");
		addItem("Bouvet Island", "BV");
		addItem("Brazil", "BR");
		addItem("British Indian Ocean Territory", "IO");
		addItem("British Virgin Islands", "VG");
		addItem("Brunei Darussalam", "BN");
		addItem("Bulgaria", "BG");
		addItem("Burkina Faso", "BF");
		addItem("Burundi", "BI");
		addItem("Cambodia", "KH");
		addItem("Cameroon", "CM");
		addItem("Canada", "CA");
		addItem("Cape Verde", "CV");
		addItem("Cayman Islands", "KY");
		addItem("Central African Republic", "CF");
		addItem("Chad", "TD");
		addItem("Chile", "CL");
		addItem("China", "CN");
		addItem("Christmas Island", "CX");
		addItem("Cocos", "CC");
		addItem("Colombia", "CO");
		addItem("Comoros", "KM");
		addItem("Congo", "CG");
		addItem("Cook Islands", "CK");
		addItem("Costa Rica", "CR");
		addItem("Croatia", "HR");
		addItem("Cuba", "CU");
		addItem("Cyprus", "CY");
		addItem("Czech Republic", "CZ");
		addItem("Denmark", "DK");
		addItem("Djibouti", "DJ");
		addItem("Dominica", "DM");
		addItem("Dominican Republic", "DO");
		addItem("East Timor", "TP");
		addItem("Ecuador", "EC");
		addItem("Egypt", "EG");
		addItem("El Salvador", "SV");
		addItem("Equatorial Guinea", "GQ");
		addItem("Eritrea", "ER");
		addItem("Estonia", "EE");
		addItem("Ethiopia", "ET");
		addItem("Falkland Islands", "FK");
		addItem("Faroe Islands", "FO");
		addItem("Fiji", "FJ");
		addItem("Finland", "FI");
		addItem("France", "FR");
		addItem("French Guiana", "GF");
		addItem("French Polynesia", "PF");
		addItem("French Southern Territories", "TF");
		addItem("Gabon", "GA");
		addItem("Gambia", "GM");
		addItem("Georgia", "GE");
		addItem("Germany", "DE");
		addItem("Ghana", "GH");
		addItem("Gibraltar", "GI");
		addItem("Greece", "GR");
		addItem("Greenland", "GL");
		addItem("Grenada", "GD");
		addItem("Guadeloupe", "GP");
		addItem("Guam", "GU");
		addItem("Guatemala", "GT");
		addItem("Guinea", "GN");
		addItem("Guinea-Bissau", "GW");
		addItem("Guyana", "GY");
		addItem("Haiti", "HT");
		addItem("Heard and McDonald Islands", "HM");
		addItem("Honduras", "HN");
		addItem("Hong Kong", "HK");
		addItem("Hungary", "HU");
		addItem("Iceland", "IS");
		addItem("India", "IN");
		addItem("Indonesia", "ID");
		addItem("Iran", "IR");
		addItem("Iraq", "IQ");
		addItem("Ireland", "IE");
		addItem("Israel", "IL");
		addItem("Italy", "IT");
		addItem("Ivory Coast", "CI");
		addItem("Jamaica", "JM");
		addItem("Japan", "JP");
		addItem("Jordan", "JO");
		addItem("Kazakhstan", "KZ");
		addItem("Kenya", "KE");
		addItem("Kiribati", "KI");
		addItem("Kuwait", "KW");
		addItem("Kyrgyzstan", "KG");
		addItem("Laos", "LA");
		addItem("Latvia", "LV");
		addItem("Lebanon", "LB");
		addItem("Lesotho", "LS");
		addItem("Liberia", "LR");
		addItem("Libya", "LY");
		addItem("Liechtenstein", "LI");
		addItem("Lithuania", "LT");
		addItem("Luxembourg", "LU");
		addItem("Macau", "MO");
		addItem("Macedonia", "MK");
		addItem("Madagascar", "MG");
		addItem("Malawi", "MW");
		addItem("Malaysia", "MY");
		addItem("Maldives", "MV");
		addItem("Mali", "ML");
		addItem("Malta", "MT");
		addItem("Marshall Islands", "MH");
		addItem("Martinique", "MQ");
		addItem("Mauritania", "MR");
		addItem("Mauritius", "MU");
		addItem("Mayotte", "YT");
		addItem("Mexico", "MX");
		addItem("Micronesia", "FM");
		addItem("Moldova", "MD");
		addItem("Monaco", "MC");
		addItem("Mongolia", "MN");
		addItem("Montserrat", "MS");
		addItem("Morocco", "MA");
		addItem("Mozambique", "MZ");
		addItem("Myanmar", "MM");
		addItem("Namibia", "NA");
		addItem("Nauru", "NR");
		addItem("Nepal", "NP");
		addItem("Netherlands", "NL");
		addItem("Netherlands Antilles", "AN");
		addItem("New Caledonia", "NC");
		addItem("New Zealand", "NZ");
		addItem("Nicaragua", "NI");
		addItem("Niger", "NE");
		addItem("Nigeria", "NG");
		addItem("Niue", "NU");
		addItem("Norfolk Island", "NF");
		addItem("North Korea", "KP");
		addItem("Northern Mariana Islands", "MP");
		addItem("Norway", "NO");
		addItem("Oman", "OM");
		addItem("Pakistan", "PK");
		addItem("Palau", "PW");
		addItem("Panama", "PA");
		addItem("Papua New Guinea", "PG");
		addItem("Paraguay", "PY");
		addItem("Peru", "PE");
		addItem("Philippines", "PH");
		addItem("Pitcairn", "PN");
		addItem("Poland", "PL");
		addItem("Portugal", "PT");
		addItem("Puerto Rico", "PR");
		addItem("Qatar", "QA");
		addItem("Reunion", "RE");
		addItem("Romania", "RO");
		addItem("Russian Federation", "RU");
		addItem("Rwanda", "RW");
		addItem("S. Georgia and S. Sandwich Islands", "GS");
		addItem("Saint Kitts and Nevis", "KN");
		addItem("Saint Lucia", "LC");
		addItem("Saint Vincent and The Grenadines", "VC");
		addItem("Samoa", "WS");
		addItem("San Marino", "SM");
		addItem("Sao Tome and Principe", "ST");
		addItem("Saudi Arabia", "SA");
		addItem("Senegal", "SN");
		addItem("Seychelles", "SC");
		addItem("Sierra Leone", "SL");
		addItem("Singapore", "SG");
		addItem("Slovakia", "SK");
		addItem("Slovenia", "SI");
		addItem("Solomon Islands", "SB");
		addItem("Somalia", "SO");
		addItem("South Africa", "ZA");
		addItem("South Korea", "KR");
		addItem("Soviet Union", "SU");
		addItem("Spain", "ES");
		addItem("Sri Lanka", "LK");
		addItem("St. Helena", "SH");
		addItem("St. Pierre and Miquelon", "PM");
		addItem("Sudan", "SD");
		addItem("Suriname", "SR");
		addItem("Svalbard and Jan Mayen Islands", "SJ");
		addItem("Swaziland", "SZ");
		addItem("Sweden", "SE");
		addItem("Switzerland", "CH");
		addItem("Syria", "SY");
		addItem("Taiwan", "TW");
		addItem("Tajikistan", "TJ");
		addItem("Tanzania", "TZ");
		addItem("Thailand", "TH");
		addItem("Togo", "TG");
		addItem("Tokelau", "TK");
		addItem("Tonga", "TO");
		addItem("Trinidad and Tobago", "TT");
		addItem("Tunisia", "TN");
		addItem("Turkey", "TR");
		addItem("Turkmenistan", "TM");
		addItem("Turks and Caicos Islands", "TC");
		addItem("Tuvalu", "TV");
		addItem("Uganda", "UG");
		addItem("Ukraine", "UA");
		addItem("United Arab Emirates", "AE");
		addItem("United Kingdom", "UK");
		addItem("United States", "US");
		addItem("Uruguay", "UY");
		addItem("US Minor Outlying Islands", "UM");
		addItem("US Virgin Islands", "VI");
		addItem("Uzbekistan", "UZ");
		addItem("Vanuatu", "VU");
		addItem("Venezuela", "VE");
		addItem("Viet Nam", "VN");
		addItem("Wallis and Futuna Islands", "WF");
		addItem("Western Sahara", "EH");
		addItem("Yemen", "YE");
		addItem("Yugoslavia", "YU");
		addItem("Zaire", "ZR");
		addItem("Zambia", "ZM");
		addItem("Zimbabwe", "ZW");		
		setSelectedIndex(0);
	}

}